substitutions:
  device_name: "akku1"
  friendly_name: Akku1
  device_description: ESP32 Marstek Battery System via RS485

packages:
  common: !include .common.yml
  marstek-e: !include .marstek-e.yml

wifi:
  use_address: 192.168.2.131

